// src/pages/index.tsx or pages/index.tsx

import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/profile-simple.jpg" alt="Profile picture" className={styles.photo} />
        <h1 className={styles.title}>
          Hi, I am Liubov Smirnova
        </h1>
        <p className={styles.description}>
            I am a student at the Innopolis University and an iOS development enthusiast.
            I am looking for collaboration on mobile, frontend, and backend development,
            so if you want to collaborate, do not hesitate to reach out to me.
        </p>
      </main>
    </div>
  );
};

export default Home;
